version: "3"

services:
  conduit_nats:
    image: nats
    ports:
      - 4222:4222

  conduit_mongo:
    image: mongo
    ports:
      - 27017:27017

  conduit_article_service:
    build:
      context: ./src/graphql/services/nodes/Article
      dockerfile: Dockerfile.test
    depends_on:
      - conduit_nats
      - conduit_mongo
    environment:
      - NATS_URL=nats://host.docker.internal:4222
      - MONGODB_URI=mongodb://host.docker.internal:27017/Test
      - DEBUG=none
      - NODE_ENV=test

  conduit_comment_service:
    build:
      context: ./src/graphql/services/nodes/Comment
      dockerfile: Dockerfile.test
    depends_on:
      - conduit_nats
      - conduit_mongo
    environment:
      - NATS_URL=nats://host.docker.internal:4222
      - MONGODB_URI=mongodb://host.docker.internal:27017/Test
      - DEBUG=none
      - NODE_ENV=test

  test_suite:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - conduit_comment_service
      - conduit_article_service
    environment:
      - NATS_URL=nats://host.docker.internal:4222
      - PORT=3000 # not needed for test, safeguard env for prod
      - MONGODB_URI=mongodb://host.docker.internal:27017/Test
      - DEBUG=none
      - SECRET=supersecret
      - NODE_ENV=test
