version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  test_suite:
    docker:
      - image: circleci/node:12.16.1
    working_directory: ~/repo
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Start Docker Network
          command: docker network create conduit_network
      - run:
          name: Build nats
          command: docker image pull nats
      - run:
          name: Start Nats
          command: docker run --network conduit_network --publish 4222:4222 --detach --name conduit_nats nats
      - run:
          name: Build mongo
          command: docker image pull mongo
      - run:
          name: Start Mongo
          command: docker run --network conduit_network --publish 27017:27017 --detach --name conduit_mongo mongo
      - run:
          name: Build Article
          command: docker build -f ./src/graphql/services/nodes/Comment/Dockerfile.test -t article ./src/graphql/services/nodes/Article/
      - run:
          name: Start Article
          command: docker run --network conduit_network --detach --name conduit_article -e NATS_URL='nats://conduit_nats:4222' -e MONGODB_URI='mongodb://conduit_mongo:27017/Test' -e DEBUG='@Conduit-Article-Service:*' -e NODE_ENV='test' article
      - run:
          name: Build Comment
          command: docker build -f ./src/graphql/services/nodes/Comment/Dockerfile.test -t comment ./src/graphql/services/nodes/Comment/
      - run:
          name: Start Comment
          command: docker run --network conduit_network --detach --name conduit_comment -e NATS_URL='nats://conduit_nats:4222' -e MONGODB_URI='mongodb://conduit_mongo:27017/Test' -e DEBUG='@Conduit-Comment-Service:*' -e NODE_ENV='test' comment
      - run:
          name: Build Gateway
          command: docker build -f ./Dockerfile.test -t gateway .
      - run:
          name: Start Gateway and test
          command: docker run --network conduit_network --name conduit_gateway -e NATS_URL='nats://conduit_nats:4222' -e MONGODB_URI='mongodb://conduit_mongo:27017/Test' -e DEBUG='@Conduit-Gateway-Service:*' -e NODE_ENV='test' gateway

workflows:
  version: 2
  master_default:
    jobs:
      - test_suite:
          filters:
            branches:
              only: /master/
