version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  test_suite:
    docker:
      - image: circleci/node:12.16.1
    working_directory: ~/repo
    steps:
      - setup_remote_docker
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run test

workflows:
  version: 2
  master_default:
    jobs:
      - test_suite:
          filters:
            branches:
              only: /master/
